# Generated by Django 4.2.5 on 2023-09-21 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_alter_token_user_alter_useraccount_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=254)),
                ('station_code', models.CharField(max_length=254)),
                ('gts_station_id', models.CharField(max_length=254)),
                ('governorate', models.CharField(max_length=254)),
                ('company_name', models.CharField(max_length=254)),
                ('phase', models.CharField(max_length=254)),
                ('inserted_by', models.CharField(default='SysAdmin', max_length=254)),
                ('insertion_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('allowances', models.PositiveBigIntegerField(default=0)),
                ('man_power_type', models.CharField(choices=[('single', 'Single Person Task'), ('multi', 'Multi Persons Task')], max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=254)),
                ('visit_date', models.DateTimeField()),
                ('notes', models.TextField()),
                ('record_date', models.DateTimeField()),
                ('area_manager_status', models.CharField(choices=[('a', 'Approved'), ('na', 'Not Approved')], max_length=254)),
                ('eng_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='engineer', to='account.useraccount')),
                ('station_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='station', to='system.station')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='task', to='system.task')),
                ('tech_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='technicion', to='account.useraccount')),
            ],
        ),
    ]
