# Generated by Django 4.2.5 on 2023-09-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='area_manager_status',
            field=models.CharField(blank=True, choices=[('a', 'Approved'), ('na', 'Not Approved')], max_length=254, null=True),
        ),
    ]
