# Generated by Django 4.2.5 on 2023-09-21 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_token_user_alter_useraccount_position'),
        ('system', '0002_alter_timesheet_area_manager_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='tech_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='technicion', to='account.useraccount'),
        ),
    ]
