# Generated by Django 4.2.5 on 2023-09-27 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_rejectedtimesheet_pendingtimesheet_approvedtimesheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvedtimesheet',
            old_name='station_code',
            new_name='station',
        ),
    ]
