# Generated by Django 4.2.5 on 2023-10-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_rename_station_code_approvedtimesheet_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
