# Generated by Django 4.2.5 on 2023-09-21 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraccount_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='account.useraccount'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='position', to='account.usertype'),
        ),
    ]
