# Generated by Django 4.2.5 on 2023-09-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_token_user_alter_useraccount_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='edit_site_data',
            field=models.BooleanField(default=False),
        ),
    ]
